# This is a basic workflow to help you get started with Actions

name: checkout the code and list the files
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Running
      - name: List the current folder
        run: ls -a
      - run: |
          ls ${{github.workspace}}
      - run: echo "${{job.status}}"
